name: Build Binaries

on:
    push:
        branches-ignore:
        - nightly
    pull_request:
        branches-ignore:
        - nightly

env:
    # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
    BUILD_TYPE: Release
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

    build_android:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Fetch container
          working-directory: ${{runner.workspace}}
          run: git clone https://github.com/AlexandreRouma/android-sdr-kit
        
        - name: Build container
          working-directory: ${{runner.workspace}}/android-sdr-kit
          run: docker build --progress=plain -t android-sdr-kit .

        - name: Build
          run: docker run --name build -v $GITHUB_WORKSPACE:/root/SDRPlusPlus android-sdr-kit /bin/bash -l -c "cd /root/SDRPlusPlus/android && gradle --info assembleDebug"

        - name: Recover APK
          working-directory: ${{runner.workspace}}
          run: docker cp build:/root/SDRPlusPlus/android/app/build/outputs/apk/debug/app-debug.apk ./ && mv app-debug.apk sdrpp.apk

        - name: Save APK
          uses: actions/upload-artifact@v4
          with:
              name: sdrpp_android
              path: ${{runner.workspace}}/sdrpp.apk

    create_full_archive:
        needs: ['build_android']
        runs-on: ubuntu-latest

        steps:
        - name: Download All Builds
          uses: actions/download-artifact@v4

        - name: Create Archive
          run: >
            mkdir sdrpp_all && 
            mv sdrpp_android/sdrpp.apk sdrpp_all/sdrpp.apk

        - uses: actions/upload-artifact@v4
          with:
            name: sdrpp_all
            path: sdrpp_all/

    update_nightly_release:
        needs: [create_full_archive]
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

        steps:
        - name: Download All Builds
          uses: actions/download-artifact@v4

        - name: Update Nightly
          run: gh release upload nightly sdrpp_all/* -R ${{github.repository}} --clobber

    check_spelling:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Install codespell
          run: sudo apt update -y && sudo apt install -y codespell
        
        - name: Running codespell
          run: cd $GITHUB_WORKSPACE && codespell -q 2 || true

    check_formatting:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        
        - name: Run check_clang_format
          run: cd $GITHUB_WORKSPACE && chmod +x ./check_clang_format.sh && ./check_clang_format.sh || true
